name: Run Infotech Webscrape Script Daily

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 17:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run script
        run: python main.py  # Replace with your script name
